### ISSUE TITLE
@tootallnate/once@1 Package is missing

### ISSUE THREAD

**Issue by gal1l0** [TooTallNate/once#1]
### The problem
Am trying to do normal `npm install` as part of my build process in my CI/CD pipeline. some odd dependency requires `http-proxy-agent` which in return has `@tootallnate/once@1` as dependency.
### What should happen
A successful `npm install`
### What's happening
am getting a 404 error
` Not Found - GET https://registry.npmjs.org/@tootallnate%2fonce - Not found`
### Supporting images
![image](https://user-images.githubusercontent.com/48126545/89521076-25330180-d7df-11ea-8562-7af49546cdc4.png)

**Comment by mattprice0009** [comment]
I am also getting this exact same issue - same stack trace and scenario (failing as a dependency of `http-proxy-agent`).

I thought I was gonna go crazy, but glad to see I'm not the only one and there's actually something going on.

**Comment by Talb2005** [comment]
I'm also experiencing this issue.
`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tootallnate%2fonce - Not found
npm ERR! 404 
npm ERR! 404  '@tootallnate/once@1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'http-proxy-agent'`

**Comment by Talb2005** [comment]
Looks like it's a problem with npm registry.. 
https://status.npmjs.org/?fbclid=IwAR2w-93OgudSMKTZv74nB1rzlvo_nGnMi3CT7bgDnfvegL-TfplEOIryY_g

**Comment by DavidYos27** [comment]
I'm having the same issue here

**Comment by TooTallNate** [comment]
Closing since this was due to an npm server issue, and is no longer an issue.
