### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by vivekkj123** [TooTallNate/once#3]
Hi there,
          While running test in your npm module, returns a error...
```
➜ npm run test 

> @tootallnate/once@1.1.2 test
> mocha --reporter spec

Error: No test files found: "test"
npm ERR! code 1
npm ERR! path /home/vivek/Downloads/node-tootallnate-once-1.1.2/once-1.1.2
npm ERR! command failed
npm ERR! command sh -c mocha --reporter spec

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vivek/.npm/_logs/2021-03-14T13_26_17_987Z-debug.log
```

**Comment by vivekkj123** [comment]
@TooTallNate Please add test or remove test from package.json

**Comment by TooTallNate** [comment]
Feel free to send a PR removing the `test` script. However, this module is more or less deprecated in favor of the Node.js core [`events.once()`](https://nodejs.org/api/events.html#events_events_once_emitter_name_options) function.
